version: '3.8' 
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local_1
    ports:
      - "6333:6333" # Port dla API REST i Dashboardu
      - "6334:6334" # Port dla gRPC
    volumes:
      - ./qdrant_data:/qdrant/storage:z
    restart: always #